Hypothesis function:

h(x) = a + bx


In [41]:
import numpy as np

In [25]:
A = np.array([1,2,3,4,5,6])

In [19]:
A

array([1, 2, 3, 4, 5])

In [20]:
A.shape

(5,)

In [27]:
B = np.reshape(A,(3,2))

In [28]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
B.shape

(3, 2)

In [39]:
B.T

array([[1, 3, 5],
       [2, 4, 6]])

array([1, 2, 3, 4, 5, 6])

In [43]:
X = np.array([[1,2],[3,4]])

In [44]:
X

array([[1, 2],
       [3, 4]])

In [45]:
X.shape

(2, 2)

In [46]:
type(X)

numpy.ndarray

In [48]:
A = X.transpose()

In [49]:
X.A

AttributeError: 'numpy.ndarray' object has no attribute 'A'

In [51]:
B = np.matmul(X,A)

In [52]:
B

array([[ 5, 11],
       [11, 25]])

In [53]:
C = np.array([1,2])

In [58]:
D = np.matmul(X,C)

In [55]:
C

array([1, 2])

In [57]:
C.shape

(2,)

In [59]:
D.shape

(2,)